run: 
	python3 -m venv run
	. ./venv/bin/activate
	pip3 install -r requirements.txt
	python3 init.py -d

dev:
	python3 -m venv dev
	. ./venv/bin/activate
	pip3 install -r requirements.txt
	python3 __database__.py
	python3 init.py -d

prod:
	echo "creati sto production"

